Future login
tomoyuki-hiranuma/lab-member-management pull request #6
Opened 2021-08-16 05:25 UTC by Hironori-Sekido

ログイン画面、ログイン情報画面を作成しました。

2021-08-16 05:34 UTC, tomoyuki-hiranuma requested changes
全体的にめちゃくちゃ良さそう！！

2021-08-16 05:34 UTC, tomoyuki-hiranuma commented on src/component/Register.tsx
> +    m: 3,
このmってmarginかな？

2021-08-17 06:06 UTC, Hironori-Sekido commented
mは余分だったので削除しました。
以下が表示されているスクリーンショットです。
![スクリーンショット 2021-08-17 14 47 13](https://user-images.githubusercontent.com/82942586/129672291-aac366c4-f5de-4f4c-a520-2419b9bcf091.png)
![スクリーンショット 2021-08-17 14 47 19](https://user-images.githubusercontent.com/82942586/129672303-a9730f04-af67-4dbb-8a99-6da0cc2993c1.png)

2021-08-17 06:22 UTC, tomoyuki-hiranuma approved these changes

2021-08-17 06:35 UTC, merged